/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_paimon_format_parquet_jni_AliParquetNativeWriter */

#ifndef _Included_org_apache_paimon_format_parquet_jni_AliParquetNativeWriter
#define _Included_org_apache_paimon_format_parquet_jni_AliParquetNativeWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeWriter
 * Method:    create
 * Signature: (Lorg/apache/paimon/fs/PositionOutputStream;JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeWriter_create
  (JNIEnv *, jobject, jobject, jlong, jstring, jint, jint);

/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeWriter
 * Method:    writeIpcBytes
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeWriter_writeIpcBytes
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeWriter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeWriter_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
