/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_paimon_format_parquet_jni_AliParquetNativeReader */

#ifndef _Included_org_apache_paimon_format_parquet_jni_AliParquetNativeReader
#define _Included_org_apache_paimon_format_parquet_jni_AliParquetNativeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeReader
 * Method:    create
 * Signature: (Lorg/apache/paimon/fs/SeekableInputStream;JLjava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeReader_create
  (JNIEnv *, jobject, jobject, jlong, jstring, jint, jboolean);

/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeReader
 * Method:    readBatch
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeReader_readBatch
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_apache_paimon_format_parquet_jni_AliParquetNativeReader
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_parquet_jni_AliParquetNativeReader_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
