/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter */

#ifndef _Included_org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter
#define _Included_org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter
 * Method:    create
 * Signature: (Lorg/apache/paimon/fs/PositionOutputStream;Ljava/lang/String;Ljava/lang/String;IIJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter_create
  (JNIEnv *, jobject, jobject, jstring, jstring, jint, jint, jlong);

/*
 * Class:     org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter
 * Method:    writeIpcBytes
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter_writeIpcBytes
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_paimon_format_aliorc_jni_AliOrcNativeWriter_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
